from pathlib import Path

out = Path('docs/generated')
out.mkdir(parents=True, exist_ok=True)

(out / 'data-dictionary.md').write_text('''# Diccionario de datos\n\n## Tabla: Flights\n\n| Campo | Tipo | Restricciones | Descripción |\n|---|---|---|---|\n| Id | integer | PK, identity | Identificador del vuelo |\n| FlightNumber | varchar(10) | NOT NULL | Código de vuelo |\n| Airline | varchar(100) | NOT NULL | Aerolínea |\n| Origin | varchar(80) | NOT NULL, index | Ciudad de origen |\n| Destination | varchar(80) | NOT NULL, index | Ciudad de destino |\n| DepartureTime | timestamp | NOT NULL, index | Salida UTC |\n| ArrivalTime | timestamp | NOT NULL | Llegada UTC |\n| Price | numeric(10,2) | NOT NULL | Precio en PEN |\n| TotalSeats | integer | NOT NULL | Capacidad total |\n\n## Tabla: Reservations\n\n| Campo | Tipo | Restricciones | Descripción |\n|---|---|---|---|\n| Id | integer | PK, identity | Identificador de reserva |\n| UserId | varchar(80) | NOT NULL | Identificador lógico del usuario |\n| PassengerName | varchar(120) | NOT NULL | Nombre del pasajero |\n| PassengerEmail | varchar(160) | NOT NULL | Correo del pasajero |\n| SeatNumber | varchar(8) | NOT NULL, UNIQUE con FlightId | Asiento |\n| CreatedAt | timestamp | NOT NULL | Fecha de creación |\n| Status | varchar(20) | NOT NULL | Confirmed/Cancelled |\n| FlightId | integer | FK Flights.Id | Vuelo reservado |\n''', encoding='utf-8')

(out / 'er-diagram.md').write_text('''# Diagrama entidad-relación\n\n```mermaid\nerDiagram\n    FLIGHTS ||--o{ RESERVATIONS : has\n    FLIGHTS {\n      int Id PK\n      string FlightNumber\n      string Airline\n      string Origin\n      string Destination\n      datetime DepartureTime\n      datetime ArrivalTime\n      decimal Price\n      int TotalSeats\n    }\n    RESERVATIONS {\n      int Id PK\n      string UserId\n      string PassengerName\n      string PassengerEmail\n      string SeatNumber\n      datetime CreatedAt\n      string Status\n      int FlightId FK\n    }\n```\n''', encoding='utf-8')

(out / 'class-diagram.md').write_text('''# Diagrama de clases\n\n```mermaid\nclassDiagram\n    class Flight {\n      +int Id\n      +string FlightNumber\n      +string Airline\n      +string Origin\n      +string Destination\n      +DateTime DepartureTime\n      +DateTime ArrivalTime\n      +decimal Price\n      +int TotalSeats\n    }\n    class Reservation {\n      +int Id\n      +string UserId\n      +string PassengerName\n      +string PassengerEmail\n      +string SeatNumber\n      +string Status\n      +int FlightId\n    }\n    class IFlightService {\n      +SearchAsync()\n      +GetByIdAsync()\n    }\n    class FlightService\n    class IReservationService {\n      +CreateAsync()\n      +GetByUserAsync()\n      +UpdateAsync()\n      +CancelAsync()\n    }\n    class ReservationService\n    Flight "1" --> "*" Reservation\n    IFlightService <|.. FlightService\n    IReservationService <|.. ReservationService\n```\n''', encoding='utf-8')

(out / 'component-diagram.md').write_text('''# Diagrama de componentes\n\n```mermaid\nflowchart LR\n    U[Usuario / Navegador] --> UI[React SPA]\n    UI --> API[ASP.NET Core REST API]\n    API --> FS[FlightService]\n    API --> RS[ReservationService]\n    FS --> EF[Entity Framework Core]\n    RS --> EF\n    EF --> DB[(PostgreSQL)]\n    GH[GitHub Actions] --> ACR[Azure Container Registry]\n    GH --> ACA[Azure Container Apps]\n```\n''', encoding='utf-8')

(out / 'deployment-diagram.md').write_text('''# Diagrama de despliegue\n\n```mermaid\nflowchart TB\n    DEV[GitHub Repository] -->|infra.yml / Terraform| AZ[Azure Resource Group]\n    DEV -->|deploy.yml| ACR[Azure Container Registry]\n    ACR --> ACA[Azure Container App]\n    USER[Internet / Browser] -->|HTTPS| ACA\n    ACA -->|TLS 5432| PG[(Azure Database for PostgreSQL Flexible Server)]\n    DEV -->|sonar.yml| SONAR[SonarQube Cloud]\n    DEV -->|snyk-semgrep.yml| SEC[Snyk + Semgrep Reports]\n```\n''', encoding='utf-8')

(out / 'README.md').write_text('''# Documentación generada\n\nEste directorio se regenera mediante `.github/workflows/generase-documentation.yml`.\n\n- `data-dictionary.md`: diccionario de datos.\n- `er-diagram.md`: diagrama entidad-relación en Mermaid.\n- `class-diagram.md`: diagrama de clases en Mermaid.\n- `component-diagram.md`: diagrama de componentes en Mermaid.\n- `deployment-diagram.md`: diagrama de despliegue en Mermaid.\n''', encoding='utf-8')
print('Documentation generated in', out)
